import { useEffect, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { AppHeader } from '@/components/AppHeader';
import { Button } from '@/components/Button';
import { Sheet } from '@/components/Sheet';
import { useSettings } from '@/hooks/useSettings';
import { isSupabaseConfigured, supabase } from '@/lib/supabase';
import { listPeople, personPhotoUrl, removePerson, savePerson } from '@/services/peopleService';
import type { PersonMemory, PersonRelationship } from '@/types';
import { ListSkeleton } from '@/components/Skeleton';
import { ContentState } from '@/components/ContentState';
import { inspectSupabase } from '@/lib/supabaseDiagnostics';
import { GUEST_PATIENT_ID } from '@/services/guestService';
import { errorLogger } from '@/services/errorLogger';
import { useI18n } from '@/i18n';

const relationships: PersonRelationship[] = ['family', 'friend', 'caregiver', 'clinician', 'other'];
const blank = (): Partial<PersonMemory> => ({ relationship: 'family', name: '', nickname: '', notes: '' });

export function People() {
  const { settings } = useSettings(); const navigate = useNavigate(); const location = useLocation(); const guest = Boolean(settings.guestMode); const localStorageMode = guest || !isSupabaseConfigured; const patientId = guest ? GUEST_PATIENT_ID : settings.activePatientId;
  const { t } = useI18n();
  const [people, setPeople] = useState<PersonMemory[]>([]); const [editing, setEditing] = useState<Partial<PersonMemory> | null>(null); const [photo, setPhoto] = useState<File | null>(null); const [voice, setVoice] = useState<File | null>(null); const [photoUrls, setPhotoUrls] = useState<Record<string, string>>({}); const [message, setMessage] = useState(''); const [connection, setConnection] = useState<'missing' | 'unauthenticated' | 'ready' | 'request-error'>(localStorageMode || isSupabaseConfigured ? 'ready' : 'missing'); const [loading, setLoading] = useState(Boolean(patientId && (localStorageMode || isSupabaseConfigured))); const [saving, setSaving] = useState(false);
  const reload = async () => { if (!patientId) return; setLoading(true); try { if (!localStorageMode) { const diagnostic = await inspectSupabase(); if (!diagnostic.clientInitialized || !supabase) { setConnection('missing'); return; } const { data: { session } } = await supabase.auth.getSession(); if (!session) { setConnection('unauthenticated'); return; } } const next = await listPeople(patientId, localStorageMode); setPeople(next); const urls = await Promise.all(next.filter((p) => p.photo_path).map(async (p) => [p.id, await personPhotoUrl(p.photo_path ?? null, localStorageMode)] as const)); setPhotoUrls(Object.fromEntries(urls.filter((entry): entry is [string, string] => Boolean(entry[1])))); setConnection('ready'); setMessage(''); } catch (error) { void errorLogger.captureRequestError(error, { feature: 'people', eventType: 'PEOPLE_LOAD_FAILED', action: 'load_people', metadata: { storageMode: localStorageMode ? 'local' : 'cloud' } }); setConnection('request-error'); setMessage(t('people.unableToLoad')); } finally { setLoading(false); } };
  useEffect(() => { void reload(); }, [patientId, guest]);
  const close = () => { if (saving) return; setEditing(null); setPhoto(null); setVoice(null); };
  const save = async () => { if (!patientId || !editing?.name?.trim()) return; setSaving(true); try { await savePerson({ ...editing, patient_id: patientId, name: editing.name.trim() }, photo, voice, localStorageMode); close(); setMessage(t('people.saved')); await reload(); } catch (error) { void errorLogger.captureRequestError(error, { feature: 'people', eventType: 'PEOPLE_SAVE_FAILED', action: 'save_person', metadata: { storageMode: localStorageMode ? 'local' : 'cloud' } }); setMessage(t('people.unableToSave')); } finally { setSaving(false); } };
  const erase = async (person: PersonMemory) => { if (!window.confirm(t('people.deleteConfirm', { name: person.name }))) return; try { await removePerson(person.id, localStorageMode); setMessage(t('people.deleted', { name: person.name })); await reload(); } catch (error) { void errorLogger.captureRequestError(error, { feature: 'people', eventType: 'PEOPLE_DELETE_FAILED', action: 'delete_person', metadata: { storageMode: localStorageMode ? 'local' : 'cloud' } }); setMessage(t('people.unableToDelete')); } };
  const back = location.pathname.startsWith('/caregiver') ? '/caregiver/patient' : '/settings';
  return <><AppHeader subtitle={t('people.title')} showBack onBack={() => navigate(back)} /><main className="page stack"><div><h1 className="page-title">{t('people.title')}</h1><p className="page-sub">{t('people.subtitle')}</p></div>
    {connection === 'missing' ? <ContentState title={t('people.noConfig')} detail={t('people.noConfigBody')} tone="amber" /> : connection === 'unauthenticated' ? <ContentState title={t('people.signInRequired')} detail={t('people.signInBody')} tone="amber" /> : connection === 'request-error' ? <ContentState title={t('people.requestFailed')} detail={t('people.requestFailedBody')} tone="amber" /> : !patientId ? <ContentState title={t('people.choosePatient')} detail={t('people.choosePatientBody')} action={{ label: t('people.goChoosePatient'), onClick: () => navigate('/caregiver/patient') }} /> : <>
      <Button size="lg" block icon="plus" onClick={() => setEditing(blank())}>{t('people.add')}</Button>
      {loading ? <ListSkeleton count={3} /> : people.length === 0 ? <ContentState title={t('people.noMembers')} detail={t('people.noMembersBody')} action={{ label: t('people.add'), onClick: () => setEditing(blank()) }} /> : <div className="people-list">{people.map((person) => <article className="person-row" key={person.id}><div className="person-row__identity">{photoUrls[person.id] ? <img src={photoUrls[person.id]} alt={`${person.name}`} width="64" height="64" loading="lazy" /> : <span className="person-row__avatar" aria-hidden="true">{person.name.charAt(0).toUpperCase()}</span>}<div className="grow"><strong>{person.name}</strong><div className="muted">{person.nickname ? `${person.nickname} · ` : ''}{person.relationship}</div>{person.notes && <p className="muted">{person.notes}</p>}</div></div><div className="person-row__actions"><Button variant="ghost" onClick={() => { setEditing(person); setPhoto(null); setVoice(null); }}>{t('common.edit')}</Button><Button variant="ghost" onClick={() => void erase(person)}>{t('common.delete')}</Button></div></article>)}</div>}
    </>}{message && <p className="banner banner--soft" role="status">{message}</p>}</main>
    <Sheet open={Boolean(editing)} title={editing?.id ? t('people.edit') : t('people.addTitle')} onClose={close}><div className="stack"><div className="field"><label className="field__label" htmlFor="person-name">{t('people.name')}</label><input id="person-name" className="input" value={editing?.name ?? ''} onChange={(e) => setEditing((value) => ({ ...value, name: e.target.value }))} autoFocus /></div><div className="field"><label className="field__label" htmlFor="person-relationship">{t('people.relationship')}</label><select id="person-relationship" className="input" value={editing?.relationship ?? 'family'} onChange={(e) => setEditing((value) => ({ ...value, relationship: e.target.value as PersonRelationship }))}>{relationships.map((relationship) => <option key={relationship} value={relationship}>{relationship}</option>)}</select></div><div className="field"><label className="field__label" htmlFor="person-nickname">{t('people.nickname')}</label><input id="person-nickname" className="input" value={editing?.nickname ?? ''} onChange={(e) => setEditing((value) => ({ ...value, nickname: e.target.value }))} /></div><div className="field"><label className="field__label" htmlFor="person-notes">{t('people.notes')}</label><textarea id="person-notes" className="input" value={editing?.notes ?? ''} onChange={(e) => setEditing((value) => ({ ...value, notes: e.target.value }))} /></div><div className="field"><label className="field__label" htmlFor="person-photo">{t('people.photo')}</label><input id="person-photo" type="file" accept="image/*" disabled={localStorageMode} onChange={(e) => setPhoto(e.target.files?.[0] ?? null)} />{localStorageMode && <small className="muted">{t('people.localMedia')}</small>}</div><div className="field"><label className="field__label" htmlFor="person-voice">{t('people.voice')}</label><input id="person-voice" type="file" accept="audio/*" disabled={localStorageMode} onChange={(e) => setVoice(e.target.files?.[0] ?? null)} /></div><div className="sheet-actions"><Button variant="ghost" onClick={close} disabled={saving}>{t('common.cancel')}</Button><Button icon="check" onClick={() => void save()} disabled={saving || !editing?.name?.trim()}>{saving ? t('people.saving') : t('people.save')}</Button></div></div></Sheet></>;
}
