import { useEffect, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { AppHeader } from '@/components/AppHeader';
import { Button } from '@/components/Button';
import { Sheet } from '@/components/Sheet';
import { useSettings } from '@/hooks/useSettings';
import { isSupabaseConfigured, supabase } from '@/lib/supabase';
import { listPeople, personPhotoUrl, removePerson, savePerson } from '@/services/peopleService';
import type { PersonMemory, PersonRelationship } from '@/types';
import { ListSkeleton } from '@/components/Skeleton';
import { ContentState } from '@/components/ContentState';
import { inspectSupabase } from '@/lib/supabaseDiagnostics';

const relationships: PersonRelationship[] = ['family', 'friend', 'caregiver', 'clinician', 'other'];
const blank = (): Partial<PersonMemory> => ({ relationship: 'family', name: '', nickname: '', notes: '' });

export function People() {
  const { settings } = useSettings(); const navigate = useNavigate(); const location = useLocation(); const patientId = settings.activePatientId; const guest = Boolean(settings.guestMode);
  const [people, setPeople] = useState<PersonMemory[]>([]); const [editing, setEditing] = useState<Partial<PersonMemory> | null>(null); const [photo, setPhoto] = useState<File | null>(null); const [voice, setVoice] = useState<File | null>(null); const [photoUrls, setPhotoUrls] = useState<Record<string, string>>({}); const [message, setMessage] = useState(''); const [connection, setConnection] = useState<'missing' | 'unauthenticated' | 'ready' | 'request-error'>(isSupabaseConfigured || guest ? 'ready' : 'missing'); const [loading, setLoading] = useState(Boolean(patientId && (isSupabaseConfigured || guest))); const [saving, setSaving] = useState(false);
  const reload = async () => { if (!patientId || (!isSupabaseConfigured && !guest)) return; setLoading(true); try { if (!guest) { const diagnostic = await inspectSupabase(); if (!diagnostic.clientInitialized || !supabase) { setConnection('missing'); return; } const { data: { session } } = await supabase.auth.getSession(); if (!session) { setConnection('unauthenticated'); return; } } const next = await listPeople(patientId); setPeople(next); const urls = await Promise.all(next.filter((p) => p.photo_path).map(async (p) => [p.id, await personPhotoUrl(p.photo_path ?? null)] as const)); setPhotoUrls(Object.fromEntries(urls.filter((entry): entry is [string, string] => Boolean(entry[1])))); setConnection('ready'); setMessage(''); } catch (error) { setConnection('request-error'); setMessage(error instanceof Error ? error.message : 'Supabase is connected, but the database or access policy rejected this request.'); } finally { setLoading(false); } };
  useEffect(() => { void reload(); }, [patientId, guest]);
  const close = () => { if (saving) return; setEditing(null); setPhoto(null); setVoice(null); };
  const save = async () => { if (!patientId || !editing?.name?.trim()) return; setSaving(true); try { await savePerson({ ...editing, patient_id: patientId, name: editing.name.trim() }, photo, voice); close(); setMessage('Family member saved successfully.'); await reload(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to save family member.'); } finally { setSaving(false); } };
  const erase = async (person: PersonMemory) => { if (!window.confirm(`Delete ${person.name}?`)) return; try { await removePerson(person.id); setMessage(`${person.name} was deleted.`); await reload(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to delete family member.'); } };
  const back = location.pathname.startsWith('/caregiver') ? '/caregiver/patient' : '/settings';
  return <><AppHeader subtitle="My People" showBack onBack={() => navigate(back)} /><main className="page stack"><div><h1 className="page-title">My People</h1><p className="page-sub">Familiar faces and helpful notes for this patient.</p></div>
    {connection === 'missing' ? <ContentState title="Supabase environment variables missing" detail="This deployment was not built with VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY." tone="amber" /> : connection === 'unauthenticated' ? <ContentState title="Sign in required" detail="Sign in with Google or email/password to securely manage this patient's people." tone="amber" /> : connection === 'request-error' ? <ContentState title="Supabase request failed" detail="Supabase is configured, but this database or RLS request failed. Check the browser diagnostic and Supabase policies." tone="amber" /> : !patientId ? <ContentState title="Choose a patient first" detail="Select an authorized patient before managing their people." action={{ label: 'Choose patient', onClick: () => navigate('/caregiver/patient') }} /> : <>
      <Button size="lg" block icon="plus" onClick={() => setEditing(blank())}>Add Family Member</Button>
      {loading ? <ListSkeleton count={3} /> : people.length === 0 ? <ContentState title="No family members yet" detail="Add familiar people, photos, and notes for personalized activities." action={{ label: 'Add Family Member', onClick: () => setEditing(blank()) }} /> : <div className="stack-sm">{people.map((person) => <div className="card row-between" key={person.id}><div className="row grow" style={{ alignItems: 'flex-start' }}>{photoUrls[person.id] ? <img src={photoUrls[person.id]} alt={`${person.name}`} width="64" height="64" loading="lazy" style={{ width: '4rem', height: '4rem', borderRadius: '9999px', objectFit: 'cover', flex: '0 0 auto' }} /> : <span className="medallion medallion--green" aria-hidden="true">{person.name.charAt(0).toUpperCase()}</span>}<div className="grow"><strong>{person.name}</strong><div className="muted">{person.nickname ? `${person.nickname} - ` : ''}{person.relationship}</div>{person.notes && <p className="muted">{person.notes}</p>}</div></div><div className="row"><Button variant="ghost" onClick={() => { setEditing(person); setPhoto(null); setVoice(null); }}>Edit</Button><Button variant="ghost" onClick={() => void erase(person)}>Delete</Button></div></div>)}</div>}
    </>}{message && <p className="banner banner--soft" role="status">{message}</p>}</main>
    <Sheet open={Boolean(editing)} title={editing?.id ? 'Edit Family Member' : 'Add Family Member'} onClose={close}><div className="stack"><div className="field"><label className="field__label" htmlFor="person-name">Name</label><input id="person-name" className="input" value={editing?.name ?? ''} onChange={(e) => setEditing((value) => ({ ...value, name: e.target.value }))} autoFocus /></div><div className="field"><label className="field__label" htmlFor="person-relationship">Relationship</label><select id="person-relationship" className="input" value={editing?.relationship ?? 'family'} onChange={(e) => setEditing((value) => ({ ...value, relationship: e.target.value as PersonRelationship }))}>{relationships.map((relationship) => <option key={relationship} value={relationship}>{relationship}</option>)}</select></div><div className="field"><label className="field__label" htmlFor="person-nickname">Nickname (optional)</label><input id="person-nickname" className="input" value={editing?.nickname ?? ''} onChange={(e) => setEditing((value) => ({ ...value, nickname: e.target.value }))} /></div><div className="field"><label className="field__label" htmlFor="person-notes">Notes (optional)</label><textarea id="person-notes" className="input" value={editing?.notes ?? ''} onChange={(e) => setEditing((value) => ({ ...value, notes: e.target.value }))} /></div><div className="field"><label className="field__label" htmlFor="person-photo">Photo (optional)</label><input id="person-photo" type="file" accept="image/*" disabled={guest} onChange={(e) => setPhoto(e.target.files?.[0] ?? null)} />{guest && <small className="muted">Photos and voice recordings need an account; guest text data remains local.</small>}</div><div className="field"><label className="field__label" htmlFor="person-voice">Voice recording (optional)</label><input id="person-voice" type="file" accept="audio/*" disabled={guest} onChange={(e) => setVoice(e.target.files?.[0] ?? null)} /></div><div className="sheet-actions"><Button variant="ghost" onClick={close} disabled={saving}>Cancel</Button><Button icon="check" onClick={() => void save()} disabled={saving || !editing?.name?.trim()}>{saving ? 'Saving…' : 'Save Family Member'}</Button></div></div></Sheet></>;
}
